TEST_VALUE:
  name: 'dev_cookie'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a4670fb045e6d00e
  FEISHU_APP_SECRET: 1HekTZU7FFGPWiIqJYKpFdrnnp7ddbuS
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
